version: "3.8"

services:
  app:
    build: .
    command: python -m userbot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata
