import time
from telethon.sync import TelegramClient
from telethon.sessions import StringSession

template = """
Contact @AISHIK999 for bot support

<b>String Session:\n<code>{}</code>
<b>DO NOT SHARE the value with anyone. Even if they say they are from Telegram</b>
"""

banner = """

@@@@@@@  @@@@@@@@  @@@@@@@@@@   @@@@@@@   @@@        @@@@@@   @@@@@@@   
@@@@@@@  @@@@@@@@  @@@@@@@@@@@  @@@@@@@@  @@@       @@@@@@@@  @@@@@@@@  
  @@!    @@!       @@! @@! @@!  @@!  @@@  @@!       @@!  @@@  @@!  @@@  
  !@!    !@!       !@! !@! !@!  !@!  @!@  !@!       !@!  @!@  !@!  @!@  
  @!!    @!!!:!    @!! !!@ @!@  @!@@!@!   @!!       @!@!@!@!  @!@!!@!   
  !!!    !!!!!:    !@!   ! !@!  !!@!!!    !!!       !!!@!!!!  !!@!@!    
  !!:    !!:       !!:     !!:  !!:       !!:       !!:  !!!  !!: :!!   
  :!:    :!:       :!:     :!:  :!:        :!:      :!:  !:!  :!:  !:!  
   ::     :: ::::  :::     ::    ::        :: ::::  ::   :::  ::   :::  
   :     : :: ::    :      :     :        : :: : :   :   : :   :   : :  

By AISHIK999
"""

print(banner)
print("\n\nThe API key and API hash can be obtained from my.telegram.org\nLog in using your Telegram account and go "
      "to API development tools\nFill in the necessary details for obtaining the values.\n\n")
time.sleep(1)

API_ID = int(input("Enter your API_ID:\n "))
API_HASH = input("Enter your API_HASH:\n ")

with TelegramClient(StringSession(), API_ID, API_HASH) as client:
    time.sleep(1)
    string_session = client.session.save()
    send_to_saved = f"STRING SESSION FOR TELEGRAM\nGenerated by Templar\n{template.format(string_session)}"
    print("\nGenerating String Session...\n")
    client.send_message("me", send_to_saved, parse_mode="html")
    print("Check your saved messages for the string session.")
